name: Greetings

on: [pull_request, issues, push]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: jfrog/setup-jfrog-cli@v1
      env:
        JF_ARTIFACTORY_1: ${{ secrets.rt_token }}
    - run: |
       # Ping the server
       jfrog rt ping
